# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

restaurants = Restaurant.create([{ rest_name: 'Terminal Velocity Aqua Bar', rest_cuisine: 'New England Seafood', rest_desc: 'Parachute into our delicious, chilly waters, and enjoy the new Engine Fried Lobstah!', rest_firstaddr: '256 Almond Avenue', rest_city: 'Wenham', rest_state: 'MA', rest_zip: '01984', rest_phone: '9788672882', rest_url: 'www.tasteofgravity.com', rest_delivers: FALSE }, { rest_name: 'Haiku Particle Collider Grill', rest_cuisine: 'Japanese', rest_desc: 'Come on in and get entangled with some preposterously delicious Bioluminescent Edamame!', rest_firstaddr: '254 Goldenrod Drive', rest_city: 'Salem', rest_state: 'MA', rest_zip: '01926', rest_phone: '9788679178', rest_fax: '9788678726', rest_url: 'www.tsubaruhaiku.com', rest_delivers: TRUE, rest_fee: 4.39, rest_menufile: 'www.tsubaruhaiku.com/menuyumyum.html' }, { rest_name: 'Yucatan Photosynthesis Eatery', rest_cuisine: 'Mexican', rest_desc: 'Get a little step in your groove and swing by for an Absolute Zero Mojito now!', rest_firstaddr: '127 Lilac Way', rest_secondaddr: '189, 2nd floor', rest_city: 'Portsmouth', rest_state: 'NH', rest_zip: '03801', rest_phone: '6036971827', rest_fax: '6039861763', rest_url: 'www.entropytaco.com', rest_delivers: TRUE, rest_fee: 2.99 }])
users = User.create([{ user_name: 'Eli Stout', user_email: 'eljasto@comcast.net', password: 'baconexplodey1', password_confirmation: 'baconexplodey1', user_role: 'admin' }, { user_name: 'Edward Einstein', user_email: 'edstone@gmail.com', password: 'esquaredequalsmc', password_confirmation: 'esquaredequalsmc', user_role: 'user' }, { user_name: 'Don Quixote De La Marzipan', user_email: 'kickdachef@yahoo.com', password: 'whyunoeatmyfewd', password_confirmation: 'whyunoeatmyfewd', user_role: 'user' }, { user_name: 'Benjamin Franklin', user_email: 'bigbucksman@gmail.com', password: 'twocentsforhundredbills', password_confirmation: 'twocentsforhundredbills', user_role: 'admin' }, { user_name: 'Jon Who', user_email: 'jon.who@gordon.edu', password: 'iamthedoctor', password_confirmation: 'iamthedoctor', user_role: 'user' }])
friends = Friend.create([{ friend_creator: 1, friend_recipient: 2 }, { friend_creator: 1, friend_recipient: 3 }, { friend_creator: 2, friend_recipient: 4 }, { friend_creator: 3, friend_recipient: 5 }])
orders = Order.create([{ order_rest: 1, order_organizer: 2, order_type: false, order_cost: 4.44, order_time_at: 4.hours.from_now, order_status: 'pending' }, { order_rest: 1, order_organizer: 1, order_type: false, order_cost: 4.44, order_time_at: 3.days.from_now, order_status: 'pending' }, { order_rest: 1, order_organizer: 2, order_type: true, order_cost: 4.44, order_time_at: DateTime.now, order_status: 'placed' }, { order_rest: 2, order_organizer: 1, order_type: false, order_cost: 4.44, order_time_at: DateTime.now, order_status: 'pending' }])
participants = Participant.create([{ part_user: 2, part_order: 1, part_role: 'organizer', part_cost: 0.00 }, { part_user: 2, part_order: 1, part_role: 'organizer', part_cost: 0.00 }, { part_user: 1, part_order: 2, part_role: 'organizer', part_cost: 0.00 }, { part_user: 2, part_order: 3, part_role: 'organizer', part_cost: 0.00 }, { part_user: 1, part_order: 4, part_role: 'organizer', part_cost: 0.00 }])
